### ISSUE TITLE
!pv relationship creation failed with errorCode ATLAS-400-00-07D

### ISSUE THREAD

**Issue by hau-mal** [tayganr/purviewcli#1]
Relationship creation is not working. Followed the sample code in relationship.ipynb:

```
typeName = 'process_dataset_outputs'
end1Guid = '2ab5525b-115a-4d82-93ea-63c33778020e'
end1Type = 'azure_datalake_gen2_path'
end2Guid = '9eb55cd7-911b-43b6-8fc6-bdf57c3e7d2a'
end2Type = 'adf_copy_activity'
!pv relationship create --typeName {typeName} --end1Guid {end1Guid} --end1Type {end1Type} --end2Guid {end2Guid} --end2Type {end2Type}
```
getting the following error:
{
    "errorCode": "ATLAS-400-00-07D",
    "errorMessage": "Relationship end is invalid. Expected Process but is NULL",
    "requestId": "b6210a2e-1a99-48b1-a80a-de18e6de413f"
}

**Comment by tayganr** [comment]
@hau-mal - I just ran the statement (with my own set of GUIDs) and it seem to work. Could you please double-check that the GUIDs in your query exist in your environment and match the expected types. The error seems to hint that end2Guid is not a process (e.g. ADF Copy Activity).

**Comment by hau-mal** [comment]
Thanks @tayganr ! Yes my fault wrong process_type.
Great to have this CLI!
