### ISSUE TITLE
APIVersionQueryParameterMissing error when running pv search query

### ISSUE THREAD

**Issue by wc12345678** [tayganr/purviewcli#12]
I am getting the following error when I run the pv search query --keywords "*" command:
{
    "errorCode": "APIVersionQueryParameterMissing",
    "errorMessage": "Please specify the query parameter api-version as one of the values in set [2021-09-01, 2021-05-01-preview] then retry.",
    "requestId": "*********-****-****-****-************"
}

Other pv commands are working as expected. Any help would be greatly appreciated.

Thanks

**Comment by tayganr** [comment]
Thanks @wc12345678 . Just published 0.1.32 which includes this query parameter and should fix `pv search query --keywords {keyword}`.
