### ISSUE TITLE
RequestInvalid error for pv entity deleteBulk

### ISSUE THREAD

**Issue by wc12345678** [tayganr/purviewcli#13]
When I run the following command: `!pv entity deleteBulk --guid="" --guid=""`

I am getting the below error:

```
{
    "errorCode": "RequestInvalid",
    "errorMessage": "Request is not recognized. Please verify the HTTP method, header or URL",
    "requestId": "xxxxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
}
```

Note that `!pv entity delete --guid=""` is working correctly

**Comment by tayganr** [comment]
Thanks @wc12345678 , fixed in [0.1.33](https://github.com/tayganr/purviewcli/releases/tag/0.1.33).
