### ISSUE TITLE
How to create terms with different template

### ISSUE THREAD

**Issue by nalol831123** [tayganr/purviewcli#17]
Hello,

We try to use the example in terms.json to set template
"templateName": []
https://github.com/tayganr/purviewcli/blob/master/samples/json/glossary/terms.json
But it doesn't works out, when we check on Purview, the template still be default
Is there any way to chose template?
Thank you

**Comment by tayganr** [comment]
@nalol831123 - Please refer to the updated [documentation](https://github.com/tayganr/purviewcli/blob/master/doc/commands/glossary/createTerms.md). If you scroll to the bottom of the page, there is an example payload (click to expand) which shows how to create terms with a custom term template.
