### ISSUE TITLE
includeTermHierarchy parameter error

### ISSUE THREAD

**Issue by nalol831123** [tayganr/purviewcli#18]
Hi,

I try to use createTermsImport to import a csv with hierarchy
When I use --includeTermHierarchy parameter, I get the following error
With --includeTermHierarchy True:
![image](https://user-images.githubusercontent.com/19884980/157612109-e190cecd-e092-44d2-bf2a-734cef21aee2.png)
Without:
![image](https://user-images.githubusercontent.com/19884980/157612022-d770ef9d-d173-411e-b43f-9547450e3698.png)

When I didn't use --includeTermHierarchy parameter, it ask me to use --includeTermHierarchy parameter

![image](https://user-images.githubusercontent.com/19884980/157611931-b0382f74-3b48-42f6-9122-89e1dd336819.png)

Am I using the correct way to use --includeTermHierarchy parameter?
Thank you!!

**Comment by tayganr** [comment]
@nalol831123 - This is a bug! Just published version 0.2.2 - this should now be fixed.
