### ISSUE TITLE
additional fields in json response for "pv scan readScanHistory"

### ISSUE THREAD

**Issue by Mada-D** [tayganr/purviewcli#19]
Hi @tayganr ,

In https://github.com/tayganr/purviewcli/blob/master/samples/notebooks%20(plus)/scan%20history.ipynb, in the "Get Scan History" - there are two additional fields in the json response that are not in your header list : ingestionJobId & webScanResults. Because of those two (new?) fields, the result is shifted and for example the last two columns don't have header. I've added the new values in my own work, but maybe you should add those here? 
headers = ["assetsClassified", "assetsDiscovered", "dataSourceType", "endTime", "error", "errorMessage", "id", "**ingestionJobId**", "parentId", "pipelineStartTime", "queuedTime", "resourceId", "runType", "scanLevelType", "scanRulesetType", "scanRulesetVersion", "startTime", "status","**webScanResults**", "source", "scanName"]

**Comment by tayganr** [comment]
Thanks @Mada-D - Example [notebook ](https://github.com/tayganr/purviewcli/blob/master/samples/notebooks%20(plus)/scan%20history.ipynb)updated to include missing headers.
