### ISSUE TITLE
`pv scan createScan` command should be implemented

### ISSUE THREAD

**Issue by nakazax** [tayganr/purviewcli#3]
It is more convenient to have a command `pv scan createScan` to copy scans between Purview accounts.

**Comment by th0ger** [comment]
Agree, there's not much meaning for me to create datasource via CLI, if I can't create scans.
Seem like an obvious miss.

**Comment by th0ger** [comment]
Here is the related endpoint definition https://docs.microsoft.com/en-us/rest/api/purview/scanningdataplane/scans/createorupdate

**Comment by tayganr** [comment]
Thanks @nakazax  and @th0ger. Just updated purviewcli (0.1.15) to align with the recent documentation on the [Scanning Data Plane](https://docs.microsoft.com/en-us/rest/api/purview/scanningdataplane/scans/createorupdate). Please see updated [scan notebook](https://github.com/tayganr/purviewcli/blob/master/samples/notebooks/scan.ipynb) which includes a section on **Scans**.

**_Example command to create or update a scan_**
`pv scan putScan --dataSourceName "DataSource2" --scanName "myScan" --payload-file "C:\Users\tarifat\Downloads\purviewcli\samples\json\scan.json"`

**Comment by nakazax** [comment]
Sorry for delayed comments in closed issue, but I've confirmed that `pv scan putScan` and some other commands work correctly with the purviewcli 0.1.17. And thanks to your fix, I've been able to create the following migration helper scripts for Purview. Thank you so much 😊
https://github.com/nakazax/purview-migration-helper
