### ISSUE TITLE
samples/sources.ipynb is outdated

### ISSUE THREAD

**Issue by pedropaulovc** [tayganr/purviewcli#4]
The [samples/sources.ipynb](/tayganr/purviewcli/blob/master/samples/sources.ipynb) file is outdated:

* Commands should be prefixed with `scan` endpoint
* `registerSource` should be `createSource`
* Azure Purview is performing validation on certain endpoints such as Azure Blob, Cosmos DB, Azure SQL etc.

**Comment by tayganr** [comment]
Thanks @pedropaulovc. Just updated purviewcli (0.1.15) to align with the recent documentation on the [Scanning Data Plane](https://docs.microsoft.com/en-us/rest/api/purview/scanningdataplane/datasources/createorupdate). Please see updated [scan notebook](https://github.com/tayganr/purviewcli/blob/master/samples/notebooks/scan.ipynb) which includes a section on **Data Sources**.

**_Example command to create or update a data source_**
`pv scan putDataSource --dataSourceName "DataSource2" --payload-file "C:\Users\tarifat\Downloads\purviewcli\samples\json\scan_source.json"`

We could build out a set of supplementary set of sample JSON files for each source? This might need some reverse engineering as the property bags do not seem to be well documented on the official MS Docs site yet...

**Comment by tayganr** [comment]
@pedropaulovc - Sample JSON documents updated to include a variety of sources (e.g. AdlsGen2, AmazonS3, Hive, etc).
https://github.com/tayganr/purviewcli/tree/master/samples/json/sources 

Along with an updated sample notebook.
https://github.com/tayganr/purviewcli/blob/master/samples/notebooks%20(plus)/sources.ipynb
