### ISSUE TITLE
Purview CLI vs. Azure CLI

### ISSUE THREAD

**Issue by th0ger** [tayganr/purviewcli#6]
I was expecing to find this functionality in (some preview version of) Azure CLI, like

```bash
az purview datasource create ...
```
Is there a particular reason for having this separate CLI?
Could (the functionality of) purviewcli be integrated into Azure CLI?

**Comment by tayganr** [comment]
Hi th0ger, purviewcli is an unofficial package. While I am employed by Microsoft, I do not work within the Azure Purview product team. Note: An official command line interface (CLI) for Azure Purview is planned, this will be made available at some point in the future.
